[project]
name = "psoriasis-robust-adv-defense"
version = "0.1.0"
description = "A Study on Collaborative Adversarial Attack-Defense Mechanisms for Robustness Enhancement in Psoriasis Medical Image Diagnosis."
authors = [
    { name = "WJ.Cao" },
    { name = "Q.Cheng" },
    { name = "YX.Li" },
    { name = "ZY.Feng" },
    { name = "YX.Li" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "pillow",
    "scipy",
    "paddlepaddle-gpu==3.3.0",
    "tqdm",
]

[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "ruff",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["psorad*"]

[[tool.uv.index]]
name = "paddle-cu130"
url = "https://www.paddlepaddle.org.cn/packages/stable/cu130/"
explicit = true

[tool.uv.sources]
paddlepaddle-gpu = { index = "paddle-cu130" }

[project.scripts]
psorad = "psorad.cli:main"
